export interface AchievementDefinition {
  id: string;
  title: string;
  description: string;
  category:
    | 'Streak'
    | 'Study Hours'
    | 'Focus Sessions'
    | 'Notes'
    | 'Quizzes'
    | 'Flashcards'
    | 'AI Usage'
    | 'Goals'
    | 'Documents'
    | 'Special';
  tier: 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY' | 'MYTHIC';
  icon: string;
  target: number;
  isSecret?: boolean;
  rewardXP: number;
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // Streak
  {
    id: 'streak_7',
    title: 'Weekly Warmup',
    description: 'Maintain a study streak for 7 days',
    category: 'Streak',
    tier: 'COMMON',
    icon: 'Flame',
    target: 7,
    rewardXP: 50,
  },
  {
    id: 'streak_30',
    title: 'Monthly Habit',
    description: 'Maintain a study streak for 30 days',
    category: 'Streak',
    tier: 'UNCOMMON',
    icon: 'Flame',
    target: 30,
    rewardXP: 150,
  },
  {
    id: 'streak_100',
    title: 'Centurion Learner',
    description: 'Maintain a study streak for 100 days',
    category: 'Streak',
    tier: 'RARE',
    icon: 'Flame',
    target: 100,
    rewardXP: 250,
  },
  {
    id: 'streak_365',
    title: 'Full Orbit',
    description: 'Maintain a study streak for 365 days',
    category: 'Streak',
    tier: 'EPIC',
    icon: 'Flame',
    target: 365,
    rewardXP: 1000,
  },
  {
    id: 'streak_1000',
    title: 'Millennium Scholar',
    description: 'Maintain a study streak for 1000 days',
    category: 'Streak',
    tier: 'LEGENDARY',
    icon: 'Flame',
    target: 1000,
    rewardXP: 5000,
  },

  // Study Hours
  {
    id: 'hours_10',
    title: 'Initiate Scholar',
    description: 'Log 10 hours of focused study time',
    category: 'Study Hours',
    tier: 'COMMON',
    icon: 'Clock',
    target: 10,
    rewardXP: 50,
  },
  {
    id: 'hours_50',
    title: 'Deep Worker',
    description: 'Log 50 hours of focused study time',
    category: 'Study Hours',
    tier: 'COMMON',
    icon: 'Clock',
    target: 50,
    rewardXP: 50,
  },
  {
    id: 'hours_100',
    title: 'Knowledge Explorer',
    description: 'Log 100 hours of focused study time',
    category: 'Study Hours',
    tier: 'UNCOMMON',
    icon: 'Clock',
    target: 100,
    rewardXP: 150,
  },
  {
    id: 'hours_250',
    title: 'Cognitive Master',
    description: 'Log 250 hours of focused study time',
    category: 'Study Hours',
    tier: 'RARE',
    icon: 'Clock',
    target: 250,
    rewardXP: 250,
  },
  {
    id: 'hours_500',
    title: 'Focus Guru',
    description: 'Log 500 hours of focused study time',
    category: 'Study Hours',
    tier: 'EPIC',
    icon: 'Clock',
    target: 500,
    rewardXP: 1000,
  },
  {
    id: 'hours_1000',
    title: 'Enlightened Sage',
    description: 'Log 1000 hours of focused study time',
    category: 'Study Hours',
    tier: 'LEGENDARY',
    icon: 'Clock',
    target: 1000,
    rewardXP: 2500,
  },
  {
    id: 'hours_5000',
    title: 'Ascended Mind',
    description: 'Log 5000 hours of focused study time',
    category: 'Study Hours',
    tier: 'MYTHIC',
    icon: 'Clock',
    target: 5000,
    rewardXP: 5000,
  },

  // Focus Sessions
  {
    id: 'focus_25',
    title: 'Pomodoro Cadet',
    description: 'Complete 25 Pomodoro sessions',
    category: 'Focus Sessions',
    tier: 'COMMON',
    icon: 'RotateCcw',
    target: 25,
    rewardXP: 50,
  },
  {
    id: 'focus_100',
    title: 'Focus Cadet',
    description: 'Complete 100 Pomodoro sessions',
    category: 'Focus Sessions',
    tier: 'UNCOMMON',
    icon: 'RotateCcw',
    target: 100,
    rewardXP: 150,
  },
  {
    id: 'focus_250',
    title: 'Time Lord',
    description: 'Complete 250 Pomodoro sessions',
    category: 'Focus Sessions',
    tier: 'RARE',
    icon: 'RotateCcw',
    target: 250,
    rewardXP: 250,
  },
  {
    id: 'focus_1000',
    title: 'Transcendental Focus',
    description: 'Complete 1000 Pomodoro sessions',
    category: 'Focus Sessions',
    tier: 'LEGENDARY',
    icon: 'RotateCcw',
    target: 1000,
    rewardXP: 2500,
  },

  // Notes
  {
    id: 'notes_25',
    title: 'Scribe',
    description: 'Create 25 study notes',
    category: 'Notes',
    tier: 'COMMON',
    icon: 'FileText',
    target: 25,
    rewardXP: 50,
  },
  {
    id: 'notes_100',
    title: 'Archivist',
    description: 'Create 100 study notes',
    category: 'Notes',
    tier: 'UNCOMMON',
    icon: 'FileText',
    target: 100,
    rewardXP: 150,
  },
  {
    id: 'notes_500',
    title: 'Librarian',
    description: 'Create 500 study notes',
    category: 'Notes',
    tier: 'RARE',
    icon: 'FileText',
    target: 500,
    rewardXP: 250,
  },
  {
    id: 'notes_1000',
    title: 'Chronicler',
    description: 'Create 1000 study notes',
    category: 'Notes',
    tier: 'EPIC',
    icon: 'FileText',
    target: 1000,
    rewardXP: 1000,
  },

  // Flashcards
  {
    id: 'cards_100',
    title: 'Memory Builder',
    description: 'Create 100 study flashcards',
    category: 'Flashcards',
    tier: 'COMMON',
    icon: 'Layers',
    target: 100,
    rewardXP: 50,
  },
  {
    id: 'cards_500',
    title: 'Retention Apprentice',
    description: 'Create 500 study flashcards',
    category: 'Flashcards',
    tier: 'UNCOMMON',
    icon: 'Layers',
    target: 500,
    rewardXP: 150,
  },
  {
    id: 'cards_2500',
    title: 'Spaced Specialist',
    description: 'Create 2500 study flashcards',
    category: 'Flashcards',
    tier: 'RARE',
    icon: 'Layers',
    target: 2500,
    rewardXP: 250,
  },
  {
    id: 'cards_10000',
    title: 'Infinite Recall',
    description: 'Create 10000 study flashcards',
    category: 'Flashcards',
    tier: 'EPIC',
    icon: 'Layers',
    target: 10000,
    rewardXP: 1000,
  },

  // Quizzes
  {
    id: 'quizzes_100',
    title: 'Quiz Rookie',
    description: 'Complete 100 academic quizzes',
    category: 'Quizzes',
    tier: 'UNCOMMON',
    icon: 'BookOpen',
    target: 100,
    rewardXP: 150,
  },
  {
    id: 'quizzes_500',
    title: 'Quiz Veteran',
    description: 'Complete 500 academic quizzes',
    category: 'Quizzes',
    tier: 'RARE',
    icon: 'BookOpen',
    target: 500,
    rewardXP: 250,
  },
  {
    id: 'quizzes_1000',
    title: 'Academic Grandmaster',
    description: 'Complete 1000 academic quizzes',
    category: 'Quizzes',
    tier: 'EPIC',
    icon: 'BookOpen',
    target: 1000,
    rewardXP: 1000,
  },
  {
    id: 'quiz_perfect_10',
    title: 'Flawless Decathlon',
    description: 'Score a perfect 100% on 10 quizzes',
    category: 'Quizzes',
    tier: 'RARE',
    icon: 'Award',
    target: 10,
    rewardXP: 250,
  },
  {
    id: 'quiz_perfect_100',
    title: 'Flawless Century',
    description: 'Score a perfect 100% on 100 quizzes',
    category: 'Quizzes',
    tier: 'LEGENDARY',
    icon: 'Award',
    target: 100,
    rewardXP: 2500,
  },

  // Goals
  {
    id: 'goals_10',
    title: 'Goal Setter',
    description: 'Complete 10 semester/study goals',
    category: 'Goals',
    tier: 'COMMON',
    icon: 'Target',
    target: 10,
    rewardXP: 50,
  },
  {
    id: 'goals_100',
    title: 'High Achiever',
    description: 'Complete 100 semester/study goals',
    category: 'Goals',
    tier: 'RARE',
    icon: 'Target',
    target: 100,
    rewardXP: 250,
  },
  {
    id: 'goals_500',
    title: 'Dream Weaver',
    description: 'Complete 500 semester/study goals',
    category: 'Goals',
    tier: 'LEGENDARY',
    icon: 'Target',
    target: 500,
    rewardXP: 2500,
  },

  // AI Usage
  {
    id: 'ai_summaries_100',
    title: 'Co-Pilot Researcher',
    description: 'Generate 100 AI notes summaries',
    category: 'AI Usage',
    tier: 'UNCOMMON',
    icon: 'Sparkles',
    target: 100,
    rewardXP: 150,
  },
  {
    id: 'ai_cards_500',
    title: 'Algorithmic Assistant',
    description: 'Generate 500 flashcards using AI generators',
    category: 'AI Usage',
    tier: 'RARE',
    icon: 'Sparkles',
    target: 500,
    rewardXP: 250,
  },
  {
    id: 'ai_quizzes_250',
    title: 'Machine Teacher',
    description: 'Generate 250 quizzes using AI',
    category: 'AI Usage',
    tier: 'RARE',
    icon: 'Sparkles',
    target: 250,
    rewardXP: 250,
  },

  // Documents
  {
    id: 'docs_25',
    title: 'Filing Clerk',
    description: 'Upload 25 documents into workspace',
    category: 'Documents',
    tier: 'COMMON',
    icon: 'Upload',
    target: 25,
    rewardXP: 50,
  },
  {
    id: 'docs_100',
    title: 'Digital Curator',
    description: 'Upload 100 documents into workspace',
    category: 'Documents',
    tier: 'RARE',
    icon: 'Upload',
    target: 100,
    rewardXP: 250,
  },
  {
    id: 'docs_500',
    title: 'Archival Master',
    description: 'Upload 500 documents into workspace',
    category: 'Documents',
    tier: 'LEGENDARY',
    icon: 'Upload',
    target: 500,
    rewardXP: 2500,
  },

  // Secret Achievements (isSecret = true)
  {
    id: 'secret_moon_reader',
    title: 'Moon Reader',
    description: 'Log a focused study session between 12 AM and 4 AM',
    category: 'Special',
    tier: 'RARE',
    icon: 'Moon',
    target: 1,
    isSecret: true,
    rewardXP: 250,
  },
  {
    id: 'secret_lightning_brain',
    title: 'Lightning Brain',
    description: 'Complete any quiz with a 100% score in less than 30 seconds',
    category: 'Special',
    tier: 'EPIC',
    icon: 'Zap',
    target: 1,
    isSecret: true,
    rewardXP: 500,
  },
  {
    id: 'secret_ancient_mind',
    title: 'Ancient Mind',
    description: 'Complete a single focus session of 120 minutes or longer',
    category: 'Special',
    tier: 'EPIC',
    icon: 'Infinity',
    target: 1,
    isSecret: true,
    rewardXP: 1000,
  },
  {
    id: 'secret_hidden_scholar',
    title: 'Hidden Scholar',
    description: 'Set your profile visibility settings to PRIVATE',
    category: 'Special',
    tier: 'UNCOMMON',
    icon: 'EyeOff',
    target: 1,
    isSecret: true,
    rewardXP: 150,
  },
  {
    id: 'secret_mystery_solver',
    title: 'Mystery Solver',
    description: 'Resolve 50 collaborative comment threads on shared notes',
    category: 'Special',
    tier: 'RARE',
    icon: 'HelpCircle',
    target: 50,
    isSecret: true,
    rewardXP: 500,
  },
];
